<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlansTableSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'slug'                    => 'free',
                'name'                    => 'Free',
                'description'             => 'Get started with basic SEO tools.',
                'price_monthly'           => 0,
                'price_yearly'            => 0,
                'projects_limit'          => 1,
                'keywords_limit'          => 10,
                'competitors_limit'       => 1,
                'scans_per_day'           => 2,
                'crawl_pages_limit'       => 0,
                'ai_credits_limit'        => 10,
                'seo_analyzer_per_day'    => 2,
                'crawl_audit_per_day'     => 0,
                'sitemap_crawler_per_day' => 0,
                'keyword_research_per_day'=> 2,
                'schema_generator_per_day'=> 1,
                'authority_checker_per_day'=> 2,
                'backlink_checker_per_day'=> 1,
                'organic_research_per_day'=> 0,
                'keyword_magic_per_day'   => 0,
                'serp_simulator_per_day'  => 3,
                'features'                => ['seo_analyzer', 'serp_simulator', 'schema_generator', 'robots_generator'],
                'is_active'               => true,
                'sort_order'              => 0,
                'trial_days'              => 0,
            ],
            [
                'slug'                    => 'pro',
                'name'                    => 'Pro',
                'description'             => 'For freelancers and small agencies.',
                'price_monthly'           => 119,
                'price_yearly'            => 1190,
                'projects_limit'          => 1,
                'keywords_limit'          => 0,
                'competitors_limit'       => 0,
                'scans_per_day'           => 10,
                'crawl_pages_limit'       => 0,
                'ai_credits_limit'        => 1000,
                'seo_analyzer_per_day'    => 10,
                'crawl_audit_per_day'     => 3,
                'sitemap_crawler_per_day' => 3,
                'keyword_research_per_day'=> 10,
                'schema_generator_per_day'=> 5,
                'authority_checker_per_day'=> 10,
                'backlink_checker_per_day'=> 5,
                'organic_research_per_day'=> 5,
                'keyword_magic_per_day'   => 3,
                'serp_simulator_per_day'  => 10,
                'features'                => ['seo_analyzer', 'serp_simulator', 'schema_generator', 'robots_generator', 'sitemap_crawler', 'crawl_audit'],
                'is_active'               => true,
                'sort_order'              => 1,
                'trial_days'              => 14,
            ],
            [
                'slug'                    => 'guru',
                'name'                    => 'Guru',
                'description'             => 'For growing SEO teams.',
                'price_monthly'           => 229,
                'price_yearly'            => 2290,
                'projects_limit'          => 15,
                'keywords_limit'          => 1500,
                'competitors_limit'       => 5,
                'scans_per_day'           => 30,
                'crawl_pages_limit'       => 150,
                'ai_credits_limit'        => 3000,
                'seo_analyzer_per_day'    => 30,
                'crawl_audit_per_day'     => 10,
                'sitemap_crawler_per_day' => 10,
                'keyword_research_per_day'=> 30,
                'schema_generator_per_day'=> 15,
                'authority_checker_per_day'=> 30,
                'backlink_checker_per_day'=> 15,
                'organic_research_per_day'=> 15,
                'keyword_magic_per_day'   => 10,
                'serp_simulator_per_day'  => 30,
                'features'                => ['all'],
                'is_active'               => true,
                'sort_order'              => 2,
                'trial_days'              => 14,
            ],
            [
                'slug'                    => 'business',
                'name'                    => 'Business',
                'description'             => 'For large agencies and enterprises.',
                'price_monthly'           => 449,
                'price_yearly'            => 4490,
                'projects_limit'          => 100,
                'keywords_limit'          => 5000,
                'competitors_limit'       => 10,
                'scans_per_day'           => 100,
                'crawl_pages_limit'       => 1000000,
                'ai_credits_limit'        => 10000,
                'seo_analyzer_per_day'    => 100,
                'crawl_audit_per_day'     => 50,
                'sitemap_crawler_per_day' => 50,
                'keyword_research_per_day'=> 100,
                'schema_generator_per_day'=> 50,
                'authority_checker_per_day'=> 100,
                'backlink_checker_per_day'=> 50,
                'organic_research_per_day'=> 50,
                'keyword_magic_per_day'   => 30,
                'serp_simulator_per_day'  => 100,
                'features'                => ['all'],
                'is_active'               => true,
                'sort_order'              => 3,
                'trial_days'              => 14,
            ],
            [
                'slug'                    => 'agency',
                'name'                    => 'Agency',
                'description'             => 'Unlimited power for white-label agencies.',
                'price_monthly'           => 999,
                'price_yearly'            => 9990,
                'projects_limit'          => null,
                'keywords_limit'          => null,
                'competitors_limit'       => null,
                'scans_per_day'           => null,
                'crawl_pages_limit'       => null,
                'ai_credits_limit'        => null,
                'seo_analyzer_per_day'    => null,
                'crawl_audit_per_day'     => null,
                'sitemap_crawler_per_day' => null,
                'keyword_research_per_day'=> null,
                'schema_generator_per_day'=> null,
                'authority_checker_per_day'=> null,
                'backlink_checker_per_day'=> null,
                'organic_research_per_day'=> null,
                'keyword_magic_per_day'   => null,
                'serp_simulator_per_day'  => null,
                'features'                => ['all'],
                'is_active'               => true,
                'sort_order'              => 4,
                'trial_days'              => 14,
            ],
        ];

        foreach ($plans as $planData) {
            Plan::updateOrCreate(
                ['slug' => $planData['slug']],
                $planData
            );
        }
    }
}
