<?php

namespace App\Services;

use App\Repositories\RobotRuleRepository;
use Illuminate\Support\Facades\Cache;
use Spatie\RobotsTxt\RobotsTxt;

class RobotsService
{
    protected RobotRuleRepository $rules;
    protected int $cacheTtl;

    protected array $aiBots = [
        'GPTBot', 'ChatGPT-User', 'anthropic-ai', 'Claude-Web',
        'diffbot', 'Bytespider', 'PerplexityBot', 'CCBot',
    ];

    protected array $pathsByType = [
        'blog' => [
            'admin' => ['/admin/', '/login/'],
            'private' => ['/private/', '/backup/'],
        ],
        'ecommerce' => [
            'admin' => ['/admin/', '/login/', '/dashboard/'],
            'private' => ['/private/', '/backup/'],
        ],
        'saas' => [
            'admin' => ['/admin/', '/login/', '/dashboard/'],
            'private' => ['/private/', '/backup/'],
        ],
        'wordpress' => [
            'admin' => ['/wp-admin/', '/wp-includes/', '/xmlrpc.php'],
            'private' => ['/private/', '/backup/'],
        ],
        'wix' => [
            'admin' => ['/admin/'],
            'private' => [],
        ],
        'static' => [
            'admin' => ['/admin/'],
            'private' => ['/private/'],
        ],
        'custom' => [
            'admin' => ['/admin/', '/login/'],
            'private' => ['/private/', '/backup/'],
        ],
    ];

    public function __construct(RobotRuleRepository $rules)
    {
        $this->rules = $rules;
        $this->cacheTtl = (int) config('seo.robots.cache_ttl', 86400);
    }

    public function buildForLevel(string $level, string $siteType = 'custom'): string
    {
        $domain = config('seo.domain', request()->getHost());
        $date = now()->format('Y-m-d');
        $header = "# Robots.txt generated by Seo4ma\n# Domain: {$domain}\n# Generated: {$date}\n\n";

        $cfg = $this->pathsByType[$siteType] ?? $this->pathsByType['custom'];

        return match ($level) {
            'minimal' => $header . $this->minimal($cfg),
            'standard' => $header . $this->standard($cfg),
            'maximum' => $header . $this->maximum($cfg),
            default => $header . $this->standard($cfg),
        };
    }

    public function validateLevel(string $level): bool
    {
        return in_array($level, ['minimal', 'standard', 'maximum', 'custom']);
    }

    private function minimal(array $cfg): string
    {
        $domain = config('seo.domain', request()->getHost());
        $sitemapUrl = config('seo.sitemap_url') ?? "https://{$domain}/sitemap.xml";

        $lines = [
            'User-agent: *',
            'Allow: /',
        ];

        foreach ($cfg['admin'] as $path) {
            $lines[] = '';
            $lines[] = "Disallow: {$path}";
        }

        $lines[] = '';
        $lines[] = "Sitemap: {$sitemapUrl}";
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function standard(array $cfg): string
    {
        $domain = config('seo.domain', request()->getHost());
        $sitemapUrl = config('seo.sitemap_url') ?? "https://{$domain}/sitemap.xml";

        $lines = [
            '# Allow all robots to crawl',
            'User-agent: *',
            'Allow: /',
            '',
            '# Admin & sensitive pages',
        ];

        foreach ($cfg['admin'] as $path) {
            $lines[] = "Disallow: {$path}";
        }
        foreach ($cfg['private'] as $path) {
            $lines[] = "Disallow: {$path}";
        }

        $lines[] = '';
        $lines[] = '# Crawl delay';
        $lines[] = 'Crawl-delay: 2';
        $lines[] = '';
        $lines[] = "Sitemap: {$sitemapUrl}";
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function maximum(array $cfg): string
    {
        $domain = config('seo.domain', request()->getHost());
        $sitemapUrl = config('seo.sitemap_url') ?? "https://{$domain}/sitemap.xml";

        $lines = [
            '# Allow all robots to crawl',
            'User-agent: *',
            'Allow: /',
            '',
            '# Admin & sensitive pages',
        ];

        foreach ($cfg['admin'] as $path) {
            $lines[] = "Disallow: {$path}";
        }
        foreach ($cfg['private'] as $path) {
            $lines[] = "Disallow: {$path}";
        }

        $lines[] = 'Disallow: /uploads/tmp/';
        $lines[] = '';
        $lines[] = '# Crawl delay';
        $lines[] = 'Crawl-delay: 5';
        $lines[] = '';
        $lines[] = '# Block AI scrapers';

        foreach ($this->aiBots as $bot) {
            $lines[] = "User-agent: {$bot}";
            $lines[] = 'Disallow: /';
            $lines[] = '';
        }

        $lines[] = '# Sitemap';
        $lines[] = "Sitemap: {$sitemapUrl}";

        return implode("\n", $lines);
    }

    public function buildRobotsContent(): string
    {
        $allRules = $this->rules->getAllActive();
        $groups = $allRules->groupBy('user_agent');
        $lines = [];
        $lines[] = '# Robots.txt — generated by Seo4ma';
        $lines[] = '# Generated: ' . now()->format('Y-m-d H:i:s');
        $lines[] = '';

        foreach ($groups as $agent => $rules) {
            $lines[] = "User-agent: {$agent}";
            $sitemapUrl = null;

            foreach ($rules as $rule) {
                $directive = $rule->rule_type === 'allow' ? 'Allow' : 'Disallow';
                $lines[] = "{$directive}: {$rule->path}";

                if ($rule->crawl_delay !== null) {
                    $lines[] = "Crawl-delay: {$rule->crawl_delay}";
                }
                if ($rule->sitemap_url && !$sitemapUrl) {
                    $sitemapUrl = $rule->sitemap_url;
                }
            }
            $lines[] = '';
        }

        $defaultSitemap = config('seo.robots.default_sitemap_url', url('/sitemap.xml'));
        $lines[] = "Sitemap: {$defaultSitemap}";
        $lines[] = '';

        return implode("\n", $lines);
    }

    public function validateRule(string $path): bool
    {
        return preg_match('#^/#', $path) === 1;
    }

    public function cacheRobots(): void
    {
        $content = $this->buildRobotsContent();
        Cache::put('robots_txt', $content, now()->addSeconds($this->cacheTtl));
    }

    public function getCachedRobots(): string
    {
        return Cache::remember('robots_txt', $this->cacheTtl, function () {
            return $this->buildRobotsContent();
        });
    }

    public function clearCache(): void
    {
        Cache::forget('robots_txt');
    }

    public function parseRobotsTxt(string $content): array
    {
        try {
            $robots = RobotsTxt::createFromString($content);
            return [
                'can_crawl' => !$robots->mayCrawl(),
                'rules' => $robots->getRules(),
            ];
        } catch (\Throwable $e) {
            return ['can_crawl' => true, 'rules' => []];
        }
    }
}
