// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/northrank-clean/CleanLight.tsx": () => import("../components/mockups/northrank-clean/CleanLight.tsx"),
  "./components/mockups/northrank-dark/DarkPro.tsx": () => import("../components/mockups/northrank-dark/DarkPro.tsx"),
  "./components/mockups/northrank-glass/GlassMorphism.tsx": () => import("../components/mockups/northrank-glass/GlassMorphism.tsx")
};
